[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmd = "npm install && npx prisma generate && npm run build"
[start]
cmd = "npm run prisma:migrate:deploy && npm run start"
